name: Deploy static site to Pages

on:
  # Roda sempre que fizer push na branch main
  push:
    branches: ["main"]

  
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Pages
        uses: actions/configure-pages@v5

      - name: Upload arquivos do site
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'   

      - name: Publicar no GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
